class ErrorCode:
    ROOM_NOT_FOUND = "ROOM_NOT_FOUND"
    INVALID_STATUS = "INVALID_STATUS"
    EXPERTS_ALREADY_GEN = "EXPERTS_ALREADY_GEN"
    LLM_TIMEOUT = "LLM_TIMEOUT"
    LLM_INVALID_RESPONSE = "LLM_INVALID_RESPONSE"
    SSE_CONNECTION_LOST = "SSE_CONNECTION_LOST"
    INTERNAL_ERROR = "INTERNAL_ERROR"
